# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7938131a7535db62679c44daccbfd726592fd32a900735abe468dc7d929a299a8fbdbfee261607596cf95dff80566e2812608ff633779b62cc51c5f416940ac4

test:
  secret_key_base: 3523e4376274356dd3d552d65e911468d099dcb2300ef2b63006417232477512fb88cf3909bd51f809c2fbaf53e0ec75fadf043ace475d259b5351f25358800d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
